events/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'events.views.list_event', name='event-list'),
    url(r'^search/$', 'events.views.search_events', name='events-list'),
    url(r'^list/$', 'events.views.list_event_api', name='event-list-api'),
    url(r'^add/$', 'events.views.add_event', name='add-event'),
    url(r'^edit/(?P<id>\w+)/$', 'events.views.edit_event', name='edit-events'),
    url(r'^delete/$', 'events.views.delete_event', name='delete-events'),
    url(r'^view/(?P<id>\w+)/$', 'events.views.events_details', name='events-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),
   
    url(r'^controllers/$', 'events.views.list_controller', name='controller-list'),
    url(r'^controller-list/$', 'events.views.controller_list', name='list-controller'),
    url(r'^controllers/add/$', 'events.views.add_controller', name='add-controller'),
    url(r'^controllers/edit/(?P<controller_name>[\w ,\']+)/$', 'events.views.edit_controller', name='edit-controller'),
    url(r'^controllers/delete/$', 'events.views.delete_controller', name='delete-controller'),
    url(r'^controllers/view/(?P<controller_name>[\w ,\']+)/$', 'events.views.controller_details', name='controller-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),


    url(r'^evententry/add/$', 'events.views.add_evententry', name='add-event-entry'),
    url(r'^evententry/delete/$', 'events.views.delete_evententry', name='delete-event-entry'),
    url(r'^evententry/edit/(?P<entryid>[\w ,\']+)/$', 'events.views.edit_evententry', name='edit-event-entry'),
    url(r'^evententry/view/(?P<entryid>[\w ,\']+)/$', 'events.views.view_evententry', name='view-event-entry'),
    url(r'^entry/list/$', 'events.views.list_evententry', name='list-event-entry'),
    
    url(r'^event-entry-list/$', 'events.views.list_evententry_api', name='list-event-entry-api'),


    url(r'^eventpayroll/add/$', 'events.views.add_eventpayroll', name='add-event-payroll'),
    url(r'^payroll/delete/$', 'events.views.delete_eventpayroll', name='delete-event-payroll'),
    url(r'^payroll/edit/(?P<serial_id>[\w ,\']+)/$', 'events.views.edit_eventpayroll', name='edit-event-payroll'),
    url(r'^payroll/view/(?P<serial_id>[\w ,\']+)/$', 'events.views.view_eventpayroll', name='view-event-payroll'),
    url(r'^payroll/list/$', 'events.views.list_eventpayroll', name='list-event-payroll'),
   
)

premierelevator/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'premierelevator.views.home', name='home'),

    url(r'^generate-pdf/$', 'premierelevator.views.generate_pdf', name='generate-pdf'),

    url(r'^system-variable/$', 'premierelevator.views.sys_variable', name='sys-variable'),
    
    url(r'^dashboard/$', 'premierelevator.views.dashboard', name='user-dashboard'),

    url(r'^send-mass-mail/$', 'premierelevator.views.send_mass_mail', name='send-mass-mail'),
    url(r'^mass-mail-status/$', 'premierelevator.views.mass_mail_status', name='mass-mail-status'),
    url(r'^get-mass-mails/$', 'premierelevator.views.get_mass_mails', name='get-mass-mail'),
    
    url(r'^group/add/$', 'premierelevator.views.add_group', name='add-group'),
    url(r'^group/list/$', 'premierelevator.views.list_group', name='list-group'),
    url(r'^group/delete/$', 'premierelevator.views.delete_group', name='delete-group'),

    #======= Angular route ===========
    url(r'^userlist/$', 'scomuser.views.UserListApi', name='userlistapi'),

    url(r'^group/edit/(?P<group_id>\d+)/$', 'premierelevator.views.edit_group', name='edit-group'),
    url(r'^group/view/(?P<group_id>\d+)/$', 'premierelevator.views.group_details', name='view-group'),

    url(r'^group/update/$', 'premierelevator.views.update_group', name='update-group'),
    url(r'^scomuser/', include('scomuser.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^purchase/', include('purchase.urls')),

    url(r'^schedule/', include('schedule.urls')),

    url(r'^selectable/', include('selectable.urls')),

    url(r'^statics/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

scomuser/urls.py
from django.conf.urls import patterns, include, url
# from scomuser.views import UserListView

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'scomuser.views.sc_home', name='scomuser-home'),
    url(r'^search/$', 'scomuser.views.search_user', name='search-user'),
    url(r'^profile/(?P<pk>\d+)/$', 'scomuser.views.UserDetails', name='scuser-profile'),
    # url(r'^edit/(?P<user_id>\d+)/$', 'scomuser.views.edit_user', name='edit-user'),
    # url(r'^profile/edit/(?P<profile_id>\d+)/$', 'scomuser.views.edit_profile', name='edit-profile'),

    url(r'^login/$', 'scomuser.views.sc_login', name='user-login'),
    url(r'^logout/$', 'scomuser.views.sc_logout', name='user-logout'),
    
    url(r'^change-password/$', 'scomuser.views.change_password2', name='change-password'),

    url(r'^adduser/$', 'scomuser.views.scomuser_add', name='adduser'),
    url(r'^userlist/$', 'scomuser.views.UserList', name='userlist'),
    url(r'^userlist/json/$', 'scomuser.views.UserListApi', name='userlist-json'),


    url(r'^list/$', 'scomuser.views.scomuser_list', name='userlistapi'),
    # url(r'^userlist/$', UserListView.as_view(), name='userlist'),
    url(r'^viewuser/(?P<pk>\d+)/$', "scomuser.views.UserDetails", name='userview'),
    url(r'^edituser/(?P<pk>\d+)/$', "scomuser.views.UserEdit", name='edituser'),
    url(r'^deleteuser/$', "scomuser.views.DeleteUser", name='deleteuser'),

    url(r'^user/report/add/$', "scomuser.views.user_report_add", name='user_report_add'),
    url(r'^user/report/delete/$', "scomuser.views.user_report_delete", name='user_report_delete'),


    url(r'^pay-types/$', "scomuser.views.list_paytype", name='list-pay-type'),
    url(r'^pay-type/add/$', "scomuser.views.add_paytype", name='add-pay-type'),
    url(r'^pay-type/edit/(?P<pay_type_id>\d+)/$', "scomuser.views.edit_paytype", name='edit-pay-type'),
    url(r'^pay-type/delete/$', "scomuser.views.delete_paytype", name='delete-pay-type'),

    url(r'^departments/$', "scomuser.views.list_department", name='list-department'),
    url(r'^department/add/$', "scomuser.views.add_department", name='add-department'),
    url(r'^department/edit/(?P<department_id>\d+)/$', "scomuser.views.edit_department", name='edit-department'),
    url(r'^department/delete/$', "scomuser.views.delete_department", name='delete-department'),

    url(r'^payrolls/$', "scomuser.views.list_payroll", name='list-payroll'),
    url(r'^payroll/(?P<payroll_id>\d+)/$', "scomuser.views.view_payroll", name='view-payroll'),
    url(r'^payroll/add/(?P<uid>\w+)/$', "scomuser.views.add_payroll", name='add-payroll'),
    url(r'^payroll/edit/(?P<payroll_id>\d+)/$', "scomuser.views.edit_payroll", name='edit-payroll'),
    url(r'^payroll/delete/$', "scomuser.views.delete_payroll", name='delete-payroll'),

    url(r'^change/password/$', 'scomuser.views.change_password', name='change-password'),    

    url(r'^permission/add/$', 'scomuser.views.scomuser_permission_add', name='scomuser-permission-add'),

    url(r'^get-change-password-form/(?P<uid>\d+)/$', 'scomuser.views.send_change_password_form')

)

scomuser/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from scomuser.choices import *
import decimal
from django.utils import timezone
from report.models import *


class ScomUserProfile(models.Model):
	user 			= models.OneToOneField(User)
	address_1 		= models.CharField(verbose_name='Address Line 1', max_length=40, null=True, blank=True)
	address_2 		= models.CharField(verbose_name='Address Line 2', max_length=40, null=True, blank=True)
	address_3 		= models.CharField(verbose_name='Address Line 3', max_length=40, null=True, blank=True)
	city 			= models.CharField(verbose_name='City', max_length=40, null=True, blank=True)
	province 		= models.CharField(verbose_name='Province', max_length=30, null=True, blank=True)
	postal 			= models.CharField(verbose_name='Postal Code', max_length=10, null=True, blank=True)
	home_phone 		= models.CharField(verbose_name='Home Phone Number', max_length=15, null=True, blank=True)
	cell_phone 		= models.CharField(verbose_name='Cell Phone Number', max_length=15, null=True, blank=True)
	other_phone 	= models.CharField(verbose_name='Other Phone Number', max_length=15, null=True, blank=True)
	internal_extension = models.CharField(verbose_name='Internal Extension', max_length=15, null=True, blank=True)
	em_contact_1 	= models.TextField(verbose_name='Primary Emergency Contact', max_length=128, null=True, blank=True)
	em_contact_2 	= models.TextField(verbose_name='Secondary Emergency Contact', max_length=128, null=True, blank=True)
	max_amount_allowed_to_purchase = models.CharField(max_length=20, null=True, blank=True)
	max_purchase_per_po = models.CharField(max_length=20, null=True, blank=True)
	avatar 			= models.ImageField(upload_to="avatar", blank=True, null=True, verbose_name="Avatar")
	search_string = models.TextField(blank=True, null=True)

	def __unicode__(self):
		return self.user.username


class Department(models.Model):
	name = models.CharField(max_length=20, blank=True, null=True)
	is_active = models.BooleanField(verbose_name='Is Active', blank=False, default=True)
	

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Department"
		verbose_name_plural = "Departments"

		permissions = (
    		('view_department', 'Can View Department'),
    	)

class UserReport(models.Model):
	user = models.ForeignKey(User, blank=True, null=True)
	report_type = models.CharField(max_length=50, choices=(('email', 'Email'), ('fax', 'Fax'), ('print', 'Print'), ('pdf', 'PDF')))
	report_printer = models.ForeignKey(Printer, blank=True, null=True)
	report_fax = models.CharField(max_length=50, blank=True, null=True)
	report_email = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.report_type
	
		




class PayType(models.Model):
	pay_type = models.CharField(max_length=20, blank=True, null=True)
	is_active = models.BooleanField(verbose_name='Is Active', blank=False, default=True)

	def __unicode__(self):
		return self.pay_type

	class Meta:
		verbose_name = "Pay Type"
		verbose_name_plural = "Pay Types"

		permissions = (
    		('view_paytype', 'Can View Pay Type'),
    	)

class Payroll(models.Model):
	user 			= models.OneToOneField(User, blank=True, null=True)
	sin   			= models.CharField(verbose_name='Employee Sin', max_length=10, null=True, blank=True)
	inital 			= models.CharField(verbose_name='Initals', max_length=3, null=True, blank=True)
	department 		= models.ForeignKey(Department, blank=True, null=True)
	rate_of_pay 	= models.DecimalField(verbose_name='Rate of Pay', max_digits=10, decimal_places=2, default=decimal.Decimal('0.00'))
	rate_of_pay_type= models.ForeignKey(PayType, null=True, blank=True)

	def __unicode__(self):
		return self.sin

	class Meta:
		verbose_name = "Payroll"
		verbose_name_plural = "Payrolls"

		permissions = (
    		('view_payroll', 'Can View payroll'),
    	)

mail_status = (
	('pending', 'Pending'),
	('delivered', 'Delivered'),
	('failed', 'Failed'),
)

class MassMail(models.Model):
	email_id = models.CharField(max_length=20, null=True, blank=True) 
	subject = models.CharField(max_length=200, null=True, blank=True)
	body = models.TextField(blank=True, null=True)
	sender = models.EmailField(max_length=100, null=True, blank=True)
	to_all_users = models.BooleanField(default=True)
	reciever = models.EmailField(max_length=100, null=True, blank=True)
	mail_status = models.CharField(verbose_name='Mail Status', max_length=10, choices=mail_status)
	request_datetime = models.DateTimeField(default=timezone.now)
	delivered_datetime = models.DateTimeField(blank=True, null=True)
	search_string = models.TextField(blank=True, null=True)


	def __unicode__(self):
		return self.email_id

	class Meta:
		verbose_name = "MassMail"
		verbose_name_plural = "MassMails"

		permissions = (
    		('view_massmail', 'Can View MassMail'),
    		('send_massmail', 'Can Send MassMail'),
    	)

templates/scomuser/partials/add-department-partial.html
<span class="label label-danger {{ department.id }}">
	{{ department.name }}
	{% if perms.scomuser.change_department %}
		<a class="department-edit" href="/scomuser/department/edit/{{ department.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-id="{{ department.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/scomuser/partials/add-pay-type-partial.html
<span class="label label-danger {{ pay_type.id }}">
	{{ pay_type.pay_type }}
	{% if perms.scomuser.change_paytype %}
		<a class="pay-type-edit" href="/scomuser/pay-type/edit/{{ pay_type.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-id="{{ pay_type.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/scomuser/partials/change-password-tpl.html
<form name="changepassword">
	<input type="hidden" name="userid" value="{{ uid }}">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title">Change Password</h4>
	</div>
	<div class="modal-body">
		
		<div class="form-group">
			<label for="exampleInputPassword1">New Password</label>
			<input type="password" class="form-control" name="newpassword" id="exampleInputPassword1" placeholder="Type New Password">
			
		</div>
		
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<button type="submit" class="btn btn-primary">Update Password</button>
	</div>
</form>

<script type="text/javascript">
(function(){
	$("form[name='changepassword']").on("submit", function(e){
		e.preventDefault();
		var form_data = $(this).serialize();
		console.log(form_data);
		$.ajax({
			type: "POST",
			url: "/scomuser/change/password/",
			data: form_data,
			success: function(rdata) {
				// $("button.close-modal").trigger("click");
				$('#changePasswordModal').modal('hide');
				alert(rdata);
				console.log(rdata);
			},
			errors: function() {

			}
		});

	});
})(jQuery)

</script>

templates/scomuser/partials/edit-department-tmpl.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Department</h4>
</div>
<form name="department-form" action="/scomuser/department/edit/{{ department_id }}/" method="post">{% csrf_token %}
<div class="modal-body">
    
    <input type="hidden" name="department_id" value="{{ department_id }}">
    <table>
        <tr>
        {% for field in department_form %}
            <td>
                {{ field }}
            </td>
        {% endfor %}
        
        </tr>
    </table>
    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
</div>
</form>
<script type="text/javascript">
(function(){
    $("form[name='department-form']").on("submit", function(e){
        e.preventDefault();
        department_id = $("input[name='department_id']").val();
        $("#department-list span."+department_id).remove();
        console.log(department_id);
        
        form_data = $(this).serialize();
        console.log(form_data);
        console.log($(this).attr("action"));
        $.ajax({
            type: "POST",
            url: $(this).attr("action"),
            data: form_data,
            success: function(rdata) {
                $( "button.close-modal" ).trigger( "click" );

                $("#department-list").prepend(rdata);

            }
        })

    })

    // $("button.close-modal").on("click", function(){
    //     pid = $("input[name='pid']").val();
    //     
    // })

})(jQuery)
    
</script>

templates/scomuser/partials/edit-pay-type-tmpl.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Pay Type</h4>
</div>
<form name="pay-type-form" action="/scomuser/pay-type/edit/{{ pay_type_id }}/" method="post">{% csrf_token %}
<div class="modal-body">
    
    <input type="hidden" name="pay_type_id" value="{{ pay_type_id }}">
    <table>
        <tr>
        {% for field in pay_type_form %}
            <td>
                {{ field }}
            </td>
        {% endfor %}
        
        </tr>
    </table>
    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
</div>
</form>
<script type="text/javascript">
(function(){
    $("form[name='pay-type-form']").on("submit", function(e){
        e.preventDefault();
        pay_type_id = $("input[name='pay_type_id']").val();
        $("#pay-type-list span."+pay_type_id).remove();
        console.log(pay_type_id);
        
        form_data = $(this).serialize();
        console.log(form_data);
        console.log($(this).attr("action"));
        $.ajax({
            type: "POST",
            url: $(this).attr("action"),
            data: form_data,
            success: function(rdata) {
                $( "button.close-modal" ).trigger( "click" );

                $("#pay-type-list").prepend(rdata);

            }
        })

    })

    // $("button.close-modal").on("click", function(){
    //     pid = $("input[name='pid']").val();
    //     
    // })

})(jQuery)
    
</script>

templates/scomuser/partials/list-department.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body">

<section class="row"  id="department">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4>Department List</h4>
		  	</div>
		  	<div class="panel-body">
		  	<form name="department-form">
		  		<div class="input-group">
				  	{% for field in department_form %}
				  		{{ field }}
				  	{% endfor %}
				  	<div class="input-group-btn">
						<button class="btn btn-primary" type="submit">Add Department</button>
					</div>
				</div>
		  	</form>
			</div>
		</div>
	</div>

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-body">
				<div id="department-list">
				{% for department in departments %}
					{% include "scomuser/partials/add-department-partial.html" %}
				{% endfor %}
				</div>
			</div>
		</div>

	</div>

{% include "modals/edit-modal.html" %}


<script type="text/javascript">
	(function(){

		$("a.department-edit").on("click", function(e){
			e.preventDefault();
			// com_id = $(this).data("id");
		    url = $(this).attr("href");
			mdal = $('#editModal');
			mdal.on("shown.bs.modal", function(){
				$("#editModal .modal-content").load(url);
				console.log(url);
			}).modal();

			return false;
		});

		$("form[name='department-form']").on("submit", function(e){
			e.preventDefault();
			form_data = $(this).serialize();

			$.ajax({
				type: "POST",
				url: "/scomuser/department/add/",
				data: form_data,
				success: function(rdata) {
					$("#department-list").append(rdata);
					console.log(rdata);
				},
				errors: function() {

				}
			})

		})

	})(jQuery)


</script>



</section>
</div>


{% endblock content %}
	

templates/scomuser/partials/list-pay-type.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body">

<section class="row"  id="pay-type">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4>Pay Type List</h4>
		  	</div>
		  	<div class="panel-body">
		  	<form name="pay-type-form">
		  		<div class="input-group">
				  	{% for field in pay_type_form %}
				  		{{ field }}
				  	{% endfor %}
				  	<div class="input-group-btn">
						<button class="btn btn-primary" type="submit">Add Pay Type</button>
					</div>
				</div>
		  	</form>
			</div>
		</div>
	</div>

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-body">
				<div id="pay-type-list">
				{% for pay_type in pay_types %}
					{% include "scomuser/partials/add-pay-type-partial.html" %}
				{% endfor %}
				</div>
			</div>
		</div>

	</div>

{% include "modals/edit-modal.html" %}


<script type="text/javascript">
	(function(){

		$("a.pay-type-edit").on("click", function(e){
			e.preventDefault();
			// com_id = $(this).data("id");
		    url = $(this).attr("href");
			mdal = $('#editModal');
			mdal.on("shown.bs.modal", function(){
				$("#editModal .modal-content").load(url);
				console.log(url);
			}).modal();

			return false;
		});

		$("form[name='pay-type-form']").on("submit", function(e){
			e.preventDefault();
			form_data = $(this).serialize();

			$.ajax({
				type: "POST",
				url: "/scomuser/pay-type/add/",
				data: form_data,
				success: function(rdata) {
					$("#pay-type-list").append(rdata);
					console.log(rdata);
				},
				errors: function() {

				}
			})

		})

	})(jQuery)


</script>



</section>
</div>


{% endblock content %}
	

templates/scomuser/partials/user-list.html
<table class="table">
	<thead>
		<tr>
			<th>User Name</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			
			<th>Is Superuser</th>
			
			<th>Last Login</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		
		<tr ng-repeat="usr in users">
			<td>{[{ usr.username }]}</td>
			<td>{[{ usr.first_name }]}</td>
			<td>{[{ usr.last_name }]}</td>
			<td>{[{ usr.email }]}</td>
			<td>{[{ usr.is_superuser }]}</td>
			
			<td>{[{ usr.last_login }]}</td>
			<td>
				<span ng-show="{{ perms.auth.can_view_user|lower }}">
				<a href="/scomuser/viewuser/{[{ usr.id }]}/"> view</a>
				</span>
				
				<span ng-show="{{ perms.auth.change_user|lower }}"> /
				<a href="/scomuser/edituser/{[{ usr.id }]}/"> Edit</a>
				</span>
				
				<span ng-show="{{ perms.auth.delete_user|lower }}"> /
				<a class="deleteuser" data-uid="{[{ usr.id }]}" href="/scomuser/deleteuser/">delete</a>
				</span>
				
				<span ng-show="{{ perms.auth.can_change_password|lower }}"> /
				<a data-toggle="modal" data-target="#changePasswordModal" class="changepassword" data-uid="{[{ usr.id }]}" href="">Change Password</a>
				</span>
				
			</td>
		</tr>
		
	</tbody>
</table>

<h2 ng-hide="users">There is no users</h2>


<div id="delete-job-confirm" style="display:none;" title="Do you want to delete?">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">
  </span>This will delete the job from your system?</p>
</div>


<script type="text/javascript">
(function() {
	$(document).on("click", "#user-list a.deleteuser", function(e){
		e.preventDefault();
		uid = $(this).data("uid");
		console.log(uid);
		$( "#delete-user-confirm" ).css("display:block;");
		
		$( "#delete-job-confirm" ).dialog({
			resizable: false,
			height:200,
			modal: true,
			buttons: {
				"Delete User": function() {
									
					$( this ).dialog( "close" );
					$.ajax({
						type: "POST",
						url: "/scomuser/deleteuser/",
						data: {
							'uid': uid,
						},
						success: function(rdata) {
							console.log(rdata);
							$("a[data-uid="+rdata+"]").closest("tr").remove();
						}
					})
				},
				Cancel: function() {
					$( this ).dialog( "close" );
				}
			}
		});

	});

	$(document).on("click", "#user-list a.changepassword", function(e){
		e.preventDefault();
		var uid = $(this).data("uid");
		console.log(uid);
		var url = "/scomuser/get-change-password-form/"+uid+"/";
		mdal = $('#changePasswordModal');
		mdal.on("shown.bs.modal", function(){
			$("#changePasswordModal .modal-content").load(url);
			console.log(url);
		}).modal();
		
		return false;

	});

	

})(jQuery)


</script>

templates/scomuser/partials/user_report_partial.html
<tr>
	<td>
		{{ user_report.report_type }}
	</td>
	{%  if user_report.report_type == 'email' %}
		<td>{{ user_report.report_email }}</td>
	{%  elif user_report.report_type == 'fax' %}
		<td>{{ user_report.report_fax }}</td>
	{%  elif user_report.report_type == 'print' %}
		<td>{{ user_report.report_printer }}</td>
	{%  elif user_report.report_type == 'pdf' %}
		<td>{{ user_report.report_pdf }}</td>
	{% endif %}
	<td>						
		<a class="user_report_delete" href="#" data-id="{{ user_report.id }}">delete</a>
	
	</td>
</tr>