events/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'events.views.list_event', name='event-list'),
    url(r'^search/$', 'events.views.search_events', name='events-list'),
    url(r'^list/$', 'events.views.list_event_api', name='event-list-api'),
    url(r'^add/$', 'events.views.add_event', name='add-event'),
    url(r'^edit/(?P<id>\w+)/$', 'events.views.edit_event', name='edit-events'),
    url(r'^delete/$', 'events.views.delete_event', name='delete-events'),
    url(r'^view/(?P<id>\w+)/$', 'events.views.events_details', name='events-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),
   
    url(r'^controllers/$', 'events.views.list_controller', name='controller-list'),
    url(r'^controller-list/$', 'events.views.controller_list', name='list-controller'),
    url(r'^controllers/add/$', 'events.views.add_controller', name='add-controller'),
    url(r'^controllers/edit/(?P<controller_name>[\w ,\']+)/$', 'events.views.edit_controller', name='edit-controller'),
    url(r'^controllers/delete/$', 'events.views.delete_controller', name='delete-controller'),
    url(r'^controllers/view/(?P<controller_name>[\w ,\']+)/$', 'events.views.controller_details', name='controller-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),


    url(r'^evententry/add/$', 'events.views.add_evententry', name='add-event-entry'),
    url(r'^evententry/delete/$', 'events.views.delete_evententry', name='delete-event-entry'),
    url(r'^evententry/edit/(?P<entryid>[\w ,\']+)/$', 'events.views.edit_evententry', name='edit-event-entry'),
    url(r'^evententry/view/(?P<entryid>[\w ,\']+)/$', 'events.views.view_evententry', name='view-event-entry'),
    url(r'^entry/list/$', 'events.views.list_evententry', name='list-event-entry'),
    
    url(r'^event-entry-list/$', 'events.views.list_evententry_api', name='list-event-entry-api'),


    url(r'^eventpayroll/add/$', 'events.views.add_eventpayroll', name='add-event-payroll'),
    url(r'^payroll/delete/$', 'events.views.delete_eventpayroll', name='delete-event-payroll'),
    url(r'^payroll/edit/(?P<serial_id>[\w ,\']+)/$', 'events.views.edit_eventpayroll', name='edit-event-payroll'),
    url(r'^payroll/view/(?P<serial_id>[\w ,\']+)/$', 'events.views.view_eventpayroll', name='view-event-payroll'),
    url(r'^payroll/list/$', 'events.views.list_eventpayroll', name='list-event-payroll'),
   
)

premierelevator/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'premierelevator.views.home', name='home'),

    url(r'^generate-pdf/$', 'premierelevator.views.generate_pdf', name='generate-pdf'),

    url(r'^system-variable/$', 'premierelevator.views.sys_variable', name='sys-variable'),
    
    url(r'^dashboard/$', 'premierelevator.views.dashboard', name='user-dashboard'),

    url(r'^send-mass-mail/$', 'premierelevator.views.send_mass_mail', name='send-mass-mail'),
    url(r'^mass-mail-status/$', 'premierelevator.views.mass_mail_status', name='mass-mail-status'),
    url(r'^get-mass-mails/$', 'premierelevator.views.get_mass_mails', name='get-mass-mail'),
    
    url(r'^group/add/$', 'premierelevator.views.add_group', name='add-group'),
    url(r'^group/list/$', 'premierelevator.views.list_group', name='list-group'),
    url(r'^group/delete/$', 'premierelevator.views.delete_group', name='delete-group'),

    #======= Angular route ===========
    url(r'^userlist/$', 'scomuser.views.UserListApi', name='userlistapi'),

    url(r'^group/edit/(?P<group_id>\d+)/$', 'premierelevator.views.edit_group', name='edit-group'),
    url(r'^group/view/(?P<group_id>\d+)/$', 'premierelevator.views.group_details', name='view-group'),

    url(r'^group/update/$', 'premierelevator.views.update_group', name='update-group'),
    url(r'^scomuser/', include('scomuser.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^purchase/', include('purchase.urls')),

    url(r'^schedule/', include('schedule.urls')),

    url(r'^selectable/', include('selectable.urls')),

    url(r'^statics/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

purchase/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^add-pr/$', 'purchase.views.add_purchase_request', name='add-purchase-request'),
    url(r'^view-pr/(?P<pk>\d+)/$', 'purchase.views.view_purchase_request', name='view-purchase-request'),
    url(r'^approve-pr/(?P<pk>\d+)/$', 'purchase.views.approve_purchase_request', name='approve-pr'),
    url(r'^declien-pr/$', 'purchase.views.declien_purchase_request', name='declien-pr'),
    url(r'^onhold-pr/$', 'purchase.views.onhold_purchase_request', name='onhold-pr'),
    url(r'^comment-pr/$', 'purchase.views.comment_purchase_request', name='comment-pr'),
    url(r'^list-purchase-requests/$', 'purchase.views.list_purchase_request', name='list-purchase-request'),
    url(r'^list-approved-pr/$', 'purchase.views.list_approved_pr', name='list-approved-pr'),
    url(r'^list-ri/json/$', 'purchase.views.list_ri_json', name='list-ri-json'),
    url(r'^request-item/delete/$', 'purchase.views.request_item_delete', name='ri-delete'),

    url(r'^add-po2/$', 'purchase.views.add_purchase_order', name='add-purchase-order'),
    
    url(r'^generate-po/(?P<po_id>\w+)/$', 'purchase.views.generate_po', name='generate-po'),
    url(r'^preview-generate-po/(?P<po_id>\w+)/$', 'purchase.views.preview_generete_po', name='preview-generate-po'),

    # url(r'^add-po/$', 'purchase.views.add_po', name='add-po'),
    url(r'^po/search/$', 'purchase.views.search_po', name='search-po'),
    url(r'^add-po/$', 'purchase.views.add_new_po', name='add-new-po'),
    url(r'^add-po-email/$', 'purchase.views.add_new_po_and_email', name='add-new-po-email'),
    # url(r'^add-po/$', 'purchase.views.add_new_po', name='add-new-po'),
    url(r'^pdf-po/(?P<po_id>\w+)/$', 'purchase.views.pdf_po', name='pdf-po'),
    url(r'^save-po/$', 'purchase.views.save_po', name='save-po'),
    # url(r'^save-po/$', 'purchase.views.save_po', name='save-po'),

    url(r'^call-contact/(?P<number>[-\w]+)/extension/(?P<ext>\w+)/$', 'purchase.views.call_number'),

    url(r'^show-draft-po/$', 'purchase.views.show_draft_po', name='draft-po'),
    url(r'^list/$', 'purchase.views.po_list', name='po-list'),
    url(r'^get-po-by-id/(?P<pk>\w+)/$', 'purchase.views.get_po_by_id', name='get-po-by-id'),


    url(r'^list-purchase-orders/$', 'purchase.views.list_purchase_orders', name='list-purchase-orders'),
    url(r'^get-purchase-orders/$', 'purchase.views.get_purchase_orders', name='get-purchase-orders'),
    # url(r'^po-items/$', 'purchase.views.get_purchase_orders', name='get-purchase-orders'),


    url(r'^view/(?P<pk>\w+)/$', 'purchase.views.view_purchase_order', name='view-purchase-order'),
    url(r'^edit/(?P<pk>\w+)/$', 'purchase.views.edit_purchase_order', name='view-purchase-order'),
    url(r'^po-delete/$', 'purchase.views.delete_purchase_order', name='delete-purchase-order'),

    url(r'^po-status-cancel/(?P<pk>\w+)/$', 'purchase.views.cancel_po_status', name='cancel-po-status'),
    url(r'^po-change/$', 'purchase.views.change_po', name='cancel-po'),

    url(r'^get-po-items/(?P<po_id>\w+)/$', 'purchase.views.get_po_items', name='get-purchase-order-items'),

    url(r'^add-supplier-extra-contact/$', 'purchase.views.add_supplier_extra_contact'),
    url(r'^add-shipto-extra-contact/$', 'purchase.views.add_shipto_extra_contact'),

    url(r'^add-sl-shipto-extra-contact/$', 'purchase.views.add_sl_shipto_extra_contact'),
    url(r'^add-sl-soldto-extra-contact/$', 'purchase.views.add_sl_soldto_extra_contact'),

    url(r'^po-extra-contact/(?P<po_id>[\w ,\'-]+)/$', 'purchase.views.extra_po_contact', name='add-extra-purchase-order-contact'),
    url(r'^delete-po-contact/$', 'purchase.views.delete_extra_po_contact', name='delete-extra-purchase-order-contact'),
    url(r'^delete-po-supplier-contact/$', 'purchase.views.delete_po_supplier_contact'),
    url(r'^delete-po-shipto-contact/$', 'purchase.views.delete_po_shipto_contact'),

    url(r'^pending-list/$', 'purchase.views.purchase_pending_list', name='purchase-pending-list'),
    url(r'^get-pending-list/$', 'purchase.views.get_pending_list', name='get-pending-list'),
    url(r'^receive-item/(?P<item_id>\d+)/$', 'purchase.views.receive_item', name='receive-item'),
    url(r'^received-list/$', 'purchase.views.purchase_received_list', name='purchase-received-list'),


    url(r'^add-pl/$', 'purchase.views.add_packing_list', name='add-packing-list'),
    url(r'^pl/search/$', 'purchase.views.search_packing_list', name='search-packing-list'),
    url(r'^get-pl/(?P<pl_number>\w+)/$', 'purchase.views.get_packing_list', name='get-packing-list'),
    
    url(r'^add-pl-soldto-extra-contact/$', 'purchase.views.add_pl_soldto_extra_contact'),
    url(r'^add-pl-shipto-extra-contact/$', 'purchase.views.add_pl_shipto_extra_contact'),
    url(r'^add-pl-cb-extra-contact/$', 'purchase.views.add_pl_cb_extra_contact'),

    url(r'^delete-pl-shipto-contact/$', 'purchase.views.delete_pl_shipto_extra_contact'),
    url(r'^delete-pl-soldto-contact/$', 'purchase.views.delete_pl_soldto_extra_contact'),
    url(r'^delete-pl-cb-contact/$', 'purchase.views.delete_pl_cb_extra_contact'),

    url(r'^view-pl/(?P<id>\w+)/$', 'purchase.views.view_packing_list', name=''),
    url(r'^edit-pl/(?P<id>\w+)/$', 'purchase.views.edit_packing_list', name='edit-packing-list'),
    url(r'^pl-delete/$', 'purchase.views.delete_packing_list', name='delete-packing-list'),
    url(r'^pl-list/$', 'purchase.views.pl_list', name='pl-list'),
    url(r'^packing-list/$', 'purchase.views.packing_list', name='packing-list'),
    url(r'^get-pl-items/(?P<pl_number>\w+)/$', 'purchase.views.get_pl_items', name='get-pl-items'),
    url(r'^get-pl-items/$', 'purchase.views.get_pl_items', name='get-pl-items'),

    url(r'^add-invoice/$', 'purchase.views.add_invoice', name='add-invoice'),
    url(r'^invoice-pdf/(?P<invoice_number>\w+)/$', 'purchase.views.generate_invoice_pdf'),
    url(r'^get-invoices/$', 'purchase.views.get_invoices', name='get-invoices'),
    url(r'^invoices/search/$', 'purchase.views.search_invoices', name='get-invoices'),
    url(r'^get-invoice-items/$', 'purchase.views.get_invoice_items', name='get-invoice-items'),
    url(r'^invoice-list/$', 'purchase.views.invoice_list', name='invoice-list'),
    url(r'^invoice-view/(?P<invoice_id>\w+)/$', 'purchase.views.invoice_view', name='invoice-list'),
    url(r'^delete-invoice/$', 'purchase.views.delete_invoice', name='delete-invoice'),

    url(r'^add-sl/$', 'purchase.views.add_shipping_list', name='add-shipping-list'),
    url(r'^generate-pl-from-sl/$', 'purchase.views.generate_pl_from_sl'),
    url(r'^delete-sl-soldto-contact/$', 'purchase.views.delete_soldto_contact'),
    url(r'^delete-sl-shipto-contact/$', 'purchase.views.delete_shipto_contact'),

    url(r'^sl/search/$', 'purchase.views.search_shiping_list', name='search-shiping-list'),
    url(r'^generate-sl/(?P<sl_number>\w+)/$', 'purchase.views.generate_sl', name='generate-sl'),
    url(r'^preview-generate-sl/(?P<sl_number>\w+)/$', 'purchase.views.preview_generete_sl', name='preview-generate-sl'),
    url(r'^generate-pl/(?P<pl_number>\w+)/$', 'purchase.views.generate_pl', name='generate-pl'),
    url(r'^preview-generate-pl/(?P<pl_id>\d+)/$', 'purchase.views.preview_generete_pl', name='preview-generate-pl'),
    url(r'^view-sl/(?P<sl_id>\w+)/$', 'purchase.views.view_shipping_list', name='view-shipping-list'),
    url(r'^edit-sl/(?P<sl_id>\w+)/$', 'purchase.views.edit_shipping_list', name='edit-shipping-list'),
    url(r'^shipping-list/$', 'purchase.views.shipping_list', name='shipping-list'),
    url(r'^sl-list-json/$', 'purchase.views.get_sl_json', name='sl-list-json'),
    url(r'^sl/(?P<sl_id>\w+)/json/$', 'purchase.views.get_sl_json_by_id', name='sl-json'),
    url(r'^sl-item-json/(?P<sl_number>\w+)/$', 'purchase.views.get_sl_item_json', name='sl-item-json'),
    url(r'^sl-item-json/$', 'purchase.views.get_sl_item_json', name='sl-item-json'),
    url(r'^sl-delete/$', 'purchase.views.sl_delete', name='sl-delete'),

    # url(r'^deliverinternal-list/$', 'purchase.views.list_deliverinternal', name='list-purchase-deliverinternal'),
    # url(r'^deliverinternals/json/$', 'purchase.views.list_deliverinternal_json', name='list-purchase-deliverinternal-json'),
    # url(r'^deliverinternal/add/$', 'purchase.views.add_deliverinternal', name='add-purchase-deliverinternal'),
    # url(r'^deliverinternal/edit/(?P<id>\d+)/$', 'purchase.views.edit_deliverinternal', name='edit-purchase-deliverinternal'),
    # url(r'^deliverinternal/delete/$', 'purchase.views.delete_deliverinternal', name='delete-purchase-deliverinternal'),

    url(r'^po/reindex/$', 'purchase.views.po_reindex', name='po-reindex'),
    url(r'^sl/reindex/$', 'purchase.views.sl_reindex', name='sl-reindex'),
    url(r'^pl/reindex/$', 'purchase.views.pl_reindex', name='pl-reindex'),
)

inventory/forms.py
from django import forms
from django.contrib import admin
from inventory.models import *
from inventory.lookups import *
from inventory.choices import *
from contacts.models import *
import selectable
from django.db import models
from django.utils.safestring import mark_safe
from premierelevator.models import SystemVariable
from django.forms import Widget, TextInput
import re
import datetime


class PremierTextInput(TextInput):
	"""docstring for PremierTextInput"""
	# def __init__(self, arg):
	# 	super(PremierTextInput, self).__init__()
	
	def render(self, name, value, attrs=None):
		str1 = TextInput.render(self, name, value, attrs)
		str2 = '<a href="/admin/contacts/contact/add/" class="add-another" id="add_id_primary_supplier" onclick="return showAddAnotherPopup(this);"> <img src="/statics/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"></a>'
		output = str1 + str2
		return mark_safe(output)

		

class ItemUnitMeasureForm(forms.ModelForm):
	class Meta:
		model = ItemUnitMeasure
		exclude = ['is_active',]


class ProductionTypeForm(forms.ModelForm):
	class Meta:
		model = ProductionType
		exclude = ['is_active',]


class CustomsDesignationForm(forms.ModelForm):
	designation = forms.CharField( max_length=25,
        widget=forms.TextInput(attrs={"class": "form-control", 'required': 'True', 'placeholder': "Custom Designation"}))

	class Meta:
		model = CustomsDesignation
		exclude = ['is_active',]


class ItemForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		self.action = kwargs.pop('action', None)
		super(ItemForm, self).__init__(*args, **kwargs)

	class Meta:
		model = Item
		# fields = ('item_number', 'description', 'currency', 'wholesale_cost', 'quantity_on_hand', 
		# 	'quantity_on_order', 'qty_on_request', 'department', 'primary_supplier', 
		# 	'item_unit_measure', 'warehouse_location', 'max_order_qty', 
		# 	'max_single_order_qty', 'estimated_wholesale_cost', 'retail_price', 'production_type',
		# 	'catalog_number', 'country_of_origin', 'lead_time', 'customs_designation', 
		# 	'customer_tariff_number', 'preference_criteria', 'producer_of_item', 'shipping_weight', 'shipping_unit',
		# 	'minimum_qty_on_hand', 'deliver_internal', 'duty_percentage', 'terms', 'website', 'item_image')

	def save(self, commit=True):
		item = super(ItemForm, self).save(commit=False)
		if self.action == 'new':
			item.max_order_qty_remains = item.max_order_qty
			# item.quantity_on_hand = 0.0;
			# item.quantity_on_order = 0.0;
			# item.qty_received = 0.0;
			# item.qty_on_request = 0.0;
			item.date_added = datetime.datetime.now();
		
		item.save()
		return item


class ItemCommentForm(forms.ModelForm):
	comment = forms.CharField( max_length=250, required=False,
        widget=forms.Textarea(attrs={"class": "form-control", 'rows':2, 'placeholder':"Item Comment"}))
	
	class Meta:
		model = ItemComment
		exclude = ['item', 'comment_date', 'comment_by']


class ItemLookupForm(forms.Form):
	autocomplete = forms.CharField(
          label='Type for auto suggession',
          widget=selectable.forms.AutoCompleteWidget(ContactLookup, 
          attrs={"class": "form-control", 'placeholder': "Filter item but item number, department and product type", 'name': 'item-autocomplete-filter'}),
          required=False,

      )



class LocationForm(forms.ModelForm):
	warehouse_location = forms.CharField( max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control", 'required': 'True', 'placeholder':"Location"}))
	description = forms.CharField( max_length=250, required=False,
        widget=forms.Textarea(attrs={"class": "form-control", 'rows':2, 'required': 'False', 'placeholder':"Location Description"}))
	
	class Meta:
		model = Location	






class DeliverInternalForm(forms.ModelForm):
    department = forms.CharField( max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control", 'required': 'True', 'placeholder':"Department"}))
    description = forms.CharField( max_length=250, required=False,
        widget=forms.Textarea(attrs={"class": "form-control", 'rows':2, 'required': 'False', 'placeholder':"Department Description"}))
    
    class Meta:
        model = DeliverInternal 

templates/purchase/add-po-supplier-contact.html
<form name="pocontact" action="/purchase/add-supplier-extra-contact/" method="POST" enctype="multipart/form-data">{% csrf_token %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myModalLabel">Add Extra Supplier Contact</h4>
</div>


<div class="modal-body">
	<table class="add-user-table">
		<tr>
			<th>Contact Type</th>
			<td>
				<select class="form-control" id="id_contact_type" name="contact_type">
					<option value="phone">Phone</option>
					<option value="email">Email</option>
					<option value="fax">Fax</option>
				</select>
			</td>
		</tr>
		<tr>
			<th>
				<label>Department</label>
			</th>
			<td>
				<input type="text" class="form-control" id="id_department" name="department">
			</td>
		</tr>
		<tr>
			<th>
				<label>Enter Phone Number</label>
			</th>
			<td>
				<input type="text" class="form-control" id="id_contact" name="contact">
			</td>
		</tr>
		<tr>
			<th>
				<label>Phone Ext</label>
			</th>
			<td>
				<input type="text" class="form-control" id="id_contact_ext" name="contact_ext">
			</td>
		</tr>
		<tr>
			<th>
				<label>Contact Name</label>
			</th>
			<td>
				<input type="text" class="form-control" id="id_contact_name" name="contact_name">
			</td>
		</tr>
	</table>
</div>



<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Add Contact</button>
</div>
</form>
<script type="text/javascript">
	(function(){

		$("form[name='pocontact']").on("submit", function(e){
			e.preventDefault();
			form_data = $(this).serialize();
			// console.log($(this).attr('action'));
			$.ajax({
				type: "POST",
				url: $(this).attr('action'),
				data: form_data,
				success: function(rdata) {
					console.log(rdata);
	                $( "button.close-modal" ).trigger( "click" );
	                // var em = "<li> mamun@gmali.com</li>";
	                var extraContactPlaceHolder = $("#supplier_extra_contact_list tbody");
	                var no = extraContactPlaceHolder.find("tr");	                
	                
	                if (no) {
	                	extraContactPlaceHolder.html(rdata);
					} else {
						extraContactPlaceHolder.append(rdata);
					}
	                
	                // window.location.reload(false);
	                // win = window.open("",'_blank');
	                // win.location.href = "/contacts/edit/" + rdata + "/";

	            }
			});

		});

		var label = $("#id_contact").closest("tr").find("label");
		var ext = $("#id_contact_ext").closest("tr");

		$('select#id_contact_type').on('change', function (e) {

		    var optionSelected = $("option:selected", this);
		    
		    var textSelected = optionSelected.text();

		    if(textSelected == 'Email') {
		    	
		    	label.text("Enter Email");
		    	ext.hide();

		    } else if(textSelected == 'Phone') {
		    	
		    	ext.show();
		    	ext.find("label").text('Enter Phone Ext');
		    	label.text("Enter Phone Number");

		    } else if(textSelected == 'Fax') {
		    	
		    	ext.show();
		    	ext.find("label").text('Enter Fax Ext');
		    	label.text("'Enter Fax Number");
		    	
		    }
		});

	})(jQuery)

</script>

templates/purchase/add-pr-comment.html
<aside class="col-md-12 comment">
	<p class="comment-text">{{ comment.comment }}</p>
	<div class="profile">
		<p class="cname">
			{{ comment.user_commented }}	
		</p>
		<p class="cdate">
			{{ comment.commnet_date }}
		</p>
		
	</div>
</aside>

templates/purchase/extra-pl-soldto-contact.html
<tr class='bg-info'>
	<td>{{plcontact.contact_type}}</td>
	<td>{{plcontact.contact}}</td>
	<td>{{plcontact.contact_name}}</td>
	<td width="">
		<a href='' data-contactid='{{plcontact.id}}' data-contacttype="soldto" class='delete-contact'>Delete</a>
		<input type='hidden' name='pl_soldto_extra_contacts' value='{{plcontact.id}}'>
	</td>
</tr>

templates/purchase/item-receive-form.html
<form name="ReceiveItem" action="/purchase/receive-item/{{item_id}}/" method="POST" enctype="multipart/form-data">{% csrf_token %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myModalLabel">Receive Item</h4>
</div>


<div class="modal-body">
	<input type="hidden" name="item_po" value="{{item_po}}">
	<input type="hidden" name="purchase_item" value="{{purchase_item}}">
	<table class="add-user-table">
		<tr>
			<td><label for="id_qty_received">Qty received:</label></td>
			<td><input class="form-control decimal" id="id_qty_received" max="{{order_restriction}}" name="qty_received" ng-model="qty" placeholder="qty received" step="0.01" type="number"></td>
		</tr>
		<tr>
			<td><label for="id_comment">Comment:</label></td>
			<td><textarea class="form-control" cols="40" id="id_comment" name="comment" placeholder="Comments" rows="2"></textarea></td>
		</tr>
	</table>
</div>



<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Add Item</button>
</div>
</form>
<script type="text/javascript">
(function(){
	$("form[name='ReceiveItem']").on("submit", function(e){
		e.preventDefault();
		form_data = $(this).serialize();
		console.log(form_data);
		$.ajax({
			type: "POST",
			url: $(this).attr('action'),
			data: form_data,
			success: function(rdata) {
                $( "button.close-modal" ).trigger( "click" );
                window.location.reload(false);
                // win = window.open("",'_blank');
                // win.location.href = "/contacts/edit/" + rdata + "/";

            }
		});

	})
})(jQuery)
</script>
    

templates/purchase/pr-approve.html
<form name="PRA" action="/purchase/approve-pr/{{pr.id}}/" method="POST" enctype="multipart/form-data" >{% csrf_token %}
<input type="hidden" name="max_limit" ng-model="max_limit" value="{{ pr.order_qty }}">
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myModalLabel">Approve</h4>
</div>


<div class="modal-body" ng-controller="ApprovePRFormController">
	<table class="add-user-table">
	
		<tbody>
			<tr>
				<td><label for="id_approved_qty">Approved qty:</label></td>
				<td><input class="form-control decimal" id="id_approved_qty" name="approved_qty" placeholder="qty" type="number" max="{{ pr.order_qty }}" required="true">

					
				</td>
			</tr>
		
		
			<tr>
				<td><label for="id_comment">Comment:</label></td>
				<td><textarea class="form-control" cols="40" id="id_comment" name="comment" rows="3"></textarea></td>
			</tr>
	
		</tbody>
	</table>
</div>



<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Approve</button>
</div>
</form>
<script type="text/javascript">
(function(){
	$("form[name='PRA']").on("submit", function(e){
		e.preventDefault();
		form_data = $(this).serialize();
		console.log(form_data);
		$.ajax({
			type: "POST",
			url: $(this).attr('action'),
			data: form_data,
			success: function(rdata) {
                $( "button.close-modal" ).trigger( "click" );
                window.location.reload(true);
                // win = window.open("",'_blank');
                // win.location.href = "/contacts/edit/" + rdata + "/";

            }
		});

	})
})(jQuery)

</script>
    